export const AuthActionConstants = {
    AUTH_ACTION_LOGIN_MAIN: '@@AUTH/LOGIN',
    AUTH_ACTION_LOGIN_ERROR: '@@AUTH/LOGIN_ERROR',
    AUTH_ACTION_LOGIN_RECIVED:'@@AUTH/LOGIN_RECIVED',
    AUTH_ACTION_LOGIN_SUCCESS:'@@AUTH/LOGIN_SUCCESS'

}